### ISSUE TITLE
Downsampling doesn't preserve null values

### ISSUE THREAD

**Issue by Bjarkias** [sveinn-steinarsson/highcharts-downsample#2]
First off, thanks a lot for this plugin and your work on downsampling. 
I've used your plugin extensively and just recently experienced a issue with it:
When downsampling discrete time series (series with null values) the gaps sometimes get sampled out. The desired functionality would be for null values to go untouched so gaps in the series are displayed correctly.

**Comment by sveinn-steinarsson** [comment]
The algorithm (LTTB) used in the plugin has some limitations: It does not support gaps (null values) in the data array and also the X-values must be in a strictly increasing order.
These limitations are documented for the Flot plugin https://github.com/sveinn-steinarsson/flot-downsample but I forgot to update the documentation for the highcharts plugin.

There are however some forks which might handle null values but I have not tested it.
One example: https://github.com/pepperdata/flot-downsample/commit/39436f81075da7e7ea0dfb3d6a72efe7fff50cc3

Gangi þér vel.
