### ISSUE TITLE
Downsampling with Dynamic X Interval

### ISSUE THREAD

**Issue by Code-Artist** [sveinn-steinarsson/highcharts-downsample#5]
Hello Sveinn,

First of all, thanks for sharing your work on LTTB algorithm. It is exactly what I am looking for to plot large data size in Microsoft Chart Component. Here is the link to my implementation in GitHub [MSChartExtension/DownSampling.cs](https://github.com/Code-Artist/MSChartExtension/blob/master/MSChartExtension/DownSampling.cs).

On top of that, I made some further improvement to address the limitation of your original LTTB algorithm to take into consideration with data with non fixed X. I wrote the description of the changes here: [Implementation of Downsampling Algorithm in MSChart Extension ](https://www.codearteng.com/2020/08/implementation-of-downsampling.html)

I would like to seek your kindness to review and comment on my work. 
I am appreciate if my work is up to standard to be listed in your list of LTTB adaptation.

Should you have any questions, you can also contact me at codearteng@gmail.com.
Hope to hear from you soon.

Regards,
Code Artist

**Comment by sveinn-steinarsson** [comment]
It is very good work and I have added the code and article link it to the README. Thank you.

**Comment by Code-Artist** [comment]
Appreciate that, thank you.
